on:
	push:
        	branches:
            		- main
        	paths:
            		- '.github/workflows/matrix.yml'
    	pull_request:
        	branches:
            		- main
        	paths:
            		- '.github/workflows/matrix.yml'
jobs:
	matrix_example:
    		strategy:
        		matrix:
        			os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
          			python-version: [3.13]
    
	runs-on: ${{matrix.os}}
	steps:
		- name: Checkout repository
          	  uses: actions/checkout@v4

		- name: Set up Python ${{ matrix.python-version }}
          	  uses: actions/setup-python@v5
          	  with:
            		python-version: ${{ matrix.python-version }}

        	- name: Install dependencies
          	  run: |
            		python -m pip install --upgrade pip
            		pip install -r requirements.txt
        
        	- name: Windows Only
          	if: runner.os == 'windows'
          	# Ensure the Python Scripts directory is in the PATH
          	run: |
            		$env:Path += ";$env:USERPROFILE\AppData\Local\Programs\Python\Python${{ matrix.python-version }}\Scripts"
			pip install pytest  
        
        	- name: Run tests
          	  run: |
            		pytest

